version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
      - MONGODB_DATA_DIR=mongodb_data
    command: mongod --auth
    ports:
      - 27025:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
